"""last_updated columns

Revision ID: b54c7861bec
Revises: 3dddf98dadce
Create Date: 2013-07-12 23:02:55.939229

"""

# revision identifiers, used by Alembic.
revision = 'b54c7861bec'
down_revision = '3dddf98dadce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('haiku', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_updated')
    op.drop_column('haiku', 'last_updated')
    ### end Alembic commands ###
